### ISSUE TITLE
Is there a way of backing up my data?

### ISSUE THREAD

**Issue by Ajaymamtora** [zenangst/KeyboardCowboy#514]

**Comment by zenangst** [comment]
Hey @Ajaymamtora, right now Keyboard Cowboy will write your configuration to ~/.keyboard-cowboy.json. If you backup that file, you should be good.

I'm working on making the storage location configurable so that you can decide if you want to use a directory which is tracked by Git or a cloud service (like iCloud, Dropbox etc) which would handle the backups and syncing for you.
